services:
  app:
    platform: linux/amd64
    image: cravyn/devops-for-programmers-project-74
    build:
      context: .
      dockerfile: Dockerfile.production
    command: make test
    depends_on:
      db:
        condition: service_healthy
    env_file:
      - ./app/.env

  db:
    image: postgres:latest
    env_file:
      - ./app/.env
    environment:
      - POSTGRES_USER=${DATABASE_USERNAME}
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
      - POSTGRES_DB=${DATABASE_NAME}
    ports:
      - "${DATABASE_PORT}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DATABASE_USERNAME} -d ${DATABASE_NAME}"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
