services:
  app:
    command: make dev
    ports:
      - "8080:8080"
    volumes:
      - ./app:/app
    depends_on:
      db:
        condition: service_healthy
  caddy:
    image: caddy:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - $PWD/services/caddy:/etc/caddy
    depends_on:
      - app
