name: push

on: push

jobs:
  test:
      runs-on: ubuntu-latest

      steps:  
        - name: Checkout code
          uses: actions/checkout@v4
          
        - name: Create .env file
          run: cp .env.example .env

        - name: Set up Docker Buildx
          uses: docker/setup-buildx-action@v3

        - name: Build test image for AMD64
          uses: docker/build-push-action@v5
          with:
            context: .
            file: Dockerfile.production
            load: true
            platforms: linux/amd64
            tags: cravyn/devops-for-programmers-project-74:latest

        - name: Run tests with Docker Compose
          run: make ci

  build-and-push:
    runs-on: ubuntu-latest
    needs: test

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: Dockerfile.production
          push: true
          platforms: linux/amd64
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/devops-for-programmers-project-74:latest
